### ISSUE TITLE
manifest for w9jds/firebase-action:v11.30.0 not found

### ISSUE THREAD

**Issue by alqamabinsadiq** [w9jds/firebase-action#187] opened 2023-05-05 06:19 UTC
My github action was working fine but for the last hour it is giving me the following error: 

<img width="892" alt="Screenshot 2023-05-05 at 11 18 28 AM" src="https://user-images.githubusercontent.com/16412803/236388959-40b5ea36-d502-4e4b-9283-d4137eeef65f.png">

**Comment by w9jds** [comment] 2023-05-05 06:30
Duplicate of #186 should be fixed now

**Closed by w9jds** 2023-05-05 06:30 UTC
