### ISSUE TITLE
Support For Workload Identity Federation/Impersonated Accounts

### ISSUE THREAD

**Issue by enchorb** [w9jds/firebase-action#123] opened 2021-12-29 20:40 UTC
Any plans to allow authenticating via impersonation & WLIF? I've provided an example below of a potential flow.

```
- id: auth
   name: Authenticate to Google Cloud
   uses: google-github-actions/auth@v0.4.1
   with:
       token_format: access_token
       access_token_lifetime: 1200s
       create_credentials_file: true
       workload_identity_provider: ...
       service_account: ${{ secrets.WLIF_SERVICE_ACCOUNT }}

  - name: Firebase
        uses: w9jds/firebase-action@master
        with:
           args: deploy --only functions
        env:
           GCP_SA_KEY: ${{ steps.auth.output.credentials_file_path }}
           --- or ---
           GCP_ACCESS_TOKEN: ${{ steps.auth.output.access_token }}
```

**Comment by enchorb** [comment] 2021-12-29 20:41
Related: https://github.com/FirebaseExtended/action-hosting-deploy/issues/174
Related: https://github.com/firebase/firebase-tools/pull/3972

**Comment by rockwotj** [comment] 2022-01-15 03:09
FWIW I have confirmed version 10.1.0 of the cli works with this auth method

**Comment by w9jds** [comment] 2022-05-14 20:27
> FWIW I have confirmed version 10.1.0 of the cli works with this auth method

If this is true, I will close this out. Feel free to re-open if that is not the case and we can look into it further.

**Closed by w9jds** 2022-05-14 20:27 UTC

**Comment by aphofstede** [comment] 2023-05-03 13:47
@w9jds Your last comment implies that this can already be done in some way? Should that be documented somewhere?

**Comment by rockwotj** [comment] 2023-05-04 03:44
See: https://github.com/firebase/firebase-tools/issues/3926

**Comment by koenmtb1** [comment] 2023-05-25 11:53
@w9jds this issue isn't fixed. It will work, but it still fails due to one of the `FIREBASE_TOKEN` or `GCP_SA_KEY` being required. Maybe it's possible to add a check if `GOOGLE_APPLICATION_CREDENTIALS` is already defined before checking if `FIREBASE_TOKEN` or `GCP_SA_KEY` is defined?
